# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_userInterface(object):
    def setupUi(self, userInterface):
        userInterface.setObjectName("userInterface")
        userInterface.resize(942, 690)
        self.modelDetails = QtWidgets.QTextEdit(userInterface)
        self.modelDetails.setGeometry(QtCore.QRect(280, 10, 561, 671))
        self.modelDetails.setObjectName("modelDetails")
        self.modelExit = QtWidgets.QPushButton(userInterface)
        self.modelExit.setGeometry(QtCore.QRect(850, 640, 81, 41))
        self.modelExit.setObjectName("modelExit")
        self.modelsList = QtWidgets.QListView(userInterface)
        self.modelsList.setGeometry(QtCore.QRect(10, 10, 256, 671))
        self.modelsList.setObjectName("modelsList")

        self.retranslateUi(userInterface)
        QtCore.QMetaObject.connectSlotsByName(userInterface)

    def retranslateUi(self, userInterface):
        _translate = QtCore.QCoreApplication.translate
        userInterface.setWindowTitle(_translate("userInterface", "Model Information"))
        self.modelExit.setText(_translate("userInterface", ">>>"))
